//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MichaelsMusic.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MichaelsMusic.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Some things are simply better in pairs. With a double-cutaway mahogany body and dual hand-wound P90 pickups from Jason Lollar, the 290 DC offers unhindered access to the upper frets and a wide range of tonal possibilities. From pristine clean tones with rich harmonic complexity to hard-hitting classic rock sounds, there are few bases the 290 DC cannot cover. To further the guitar&apos;s vintage-inspired tone and aesthetic, we&apos;ve made available our own custom wraparound tailpiece (optional) that&apos;s been designe [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Collings_290_DC_Description {
            get {
                return ResourceManager.GetString("Collings_290_DC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Crafted with the finest seasoned maple and Honduran mahogany, the CL Deluxe is built for tone. Lightweight, resonant mahogany combined with a carefully hand-set mortise and tenon neck joint bring tonal complexity and sustain to the table in spades. The CL Deluxe features ivoroid neck and peghead binding and our custom ivoroid &quot;top hat&quot; knobs and pickup rings. Sleekly contoured for comfort and style, we&apos;ve brought new life to an American classic.&lt;/p&gt;
        ///&lt;h3&gt;Premium Tonewoods&lt;/h3&gt;
        ///&lt;p&gt;Each Collings Deluxe el [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Collings_CL_Deluxe_Description {
            get {
                return ResourceManager.GetString("Collings_CL_Deluxe_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The G&amp;amp;L Legacy™ blends contemporary refinements from the Leo Fender†-designed S-500™ and Comanche® models with classic Alnico V pickups. If your holy grail is faithful Alnico single-coil tone with modern refinements and superb craftsmanship, the Legacy makes for an excellent choice.&lt;/p&gt;
        ///&lt;p&gt;The Legacy’s vintage-spec CLF-100 Alnico V pickups have that unmistakable chime and quack reminiscent of the best examples from the late ‘50s, thanks to the work of Paul Gagon, G&amp;amp;L VP Engineering. Gagon found  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GL_Legacy_Description {
            get {
                return ResourceManager.GetString("GL_Legacy_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The McNaught Vintage Double Cut is a Mahogany solid body carved top guitar with a Mahogany &apos;SET-THRU&apos; neck and &apos;All-Access&apos; heel. It features a flame Maple bound Indian Rosewood fingerboard with 12\&quot; radius, 22 frets, 24 3/4\&quot; compensated scale length, Mother Of Pearl &apos;Offset Block&apos; inlays, Tone Pros Tune-O-Matic bridge, Sperzel locking tuners, Wagner Dual humbuckers, 1 11/16\&quot; nut, matching wood cavity covers, and a standard form-fitted case.&lt;/p&gt;
        ///&lt;p&gt;Available custom upgrades include:&lt;/p&gt;
        ///&lt;ul&gt;
        ///    &lt;li [rest of string was truncated]&quot;;.
        /// </summary>
        public static string McNaught_VDC_Description {
            get {
                return ResourceManager.GetString("McNaught_VDC_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;The Custom 24 is the quintessential PRS guitar. This iconic instrument was the first model that Paul Reed Smith brought to the public at PRS Guitars’ first Winter NAMM show in 1985 and has been a top seller ever since. Played by internationally touring artists, gigging musicians, and aspiring players, the Custom 24 features PRS’s patented tremolo system and PRS 85/15 treble and bass pickups with volume and tone controls and a 5-way blade switch. 85/15 pickups were personally designed by Paul Reed Smith f [rest of string was truncated]&quot;;.
        /// </summary>
        public static string PRS_Custom24_Description {
            get {
                return ResourceManager.GetString("PRS_Custom24_Description", resourceCulture);
            }
        }
    }
}
